version: '3.8'

services:
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    image: musharrafmm/backend:${BUILD_NUMBER}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    image: musharrafmm/frontend:${BUILD_NUMBER}
    ports:
      - "3000:80"
